---

- name: http
  package:
    name: httpie
    state: latest

- name: install haproxy
  yum:
    name=haproxy 
    state=latest

- name: enable haproxy
  service:
    name: haproxy
    state: started

- name: enable haproxy
  service:
    name: haproxy
    state: started

- name: configure haproxy to load balance over app servers
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: restart HAPRoxy
  service:
    name: haproxy
    state: restarted

